User + Role
chumomega/pranker pull request #16
Opened 2022-03-18 19:27 UTC by Jakarai

## What does this PR do?
Added user and Roles system

## How can others know that your changes do what you say they do? Can you please share some testing steps?

After running the main class, you can then go to 'Localhost:9001/api/prankers', then you should see a login screen generated by Spring. enter 'user' for the username and use the spring generated password, as the password. you should than see a JSON array of users.

<img width="1545" alt="Screen Shot 2022-03-18 at 3 22 19 PM" src="https://user-images.githubusercontent.com/56364114/159071108-b55eb5fd-595b-48ec-af57-9b21f417cefa.png">

## Screenshots (if user facing change)

## Checklist before merging
- [ ] Someone has given this PR an approval and thorough review
- [ ] I have validated that I have not broken something else in
<img width="1355" alt="Screen Shot 2022-03-18 at 3 20 15 PM" src="https://user-images.githubusercontent.com/56364114/159070387-69014ef4-cff2-44c1-bf44-eb547fa31e26.png">
 the code

2022-03-19 19:23 UTC, chumomega requested changes
bro you ain't notice that this pr is adding 2million lines of code lol?
the pranker frontend stuff doesn't belong in this repo. and even if it did, we don't need the node_modules since that can be geneerated locally using npm install

2022-03-19 19:38 UTC, Jakarai commented
Nah this is madness, I had no clue All that code was being added, not sure how it even got there.

2022-03-19 19:40 UTC, Jakarai commented
Im guessing my dev branch still had the old code with the frontend still attached instead of separate repos.

2022-03-23 16:53 UTC, chumomega commented on src/main/resources/application.properties
> +server.port=9001
why are you changing the port?

2022-03-23 16:56 UTC, chumomega commented on src/main/java/com/v2/pranker/PrankerApplication.java
> +			prankerService.saveRole(new Role(null, "Role_User"));
these run sql commands in the background right? could we try to remove this and just add this mock data locally (either some sql script or manually)?

2022-03-23 16:57 UTC, chumomega commented on src/main/java/com/v2/pranker/controller/PrankerController.java
> +    @GetMapping("/prankers")
why would we need to get all prankers?

2022-03-23 16:58 UTC, chumomega commented on src/main/java/com/v2/pranker/controller/PrankerController.java
> +    public ResponseEntity<Role>saveRole(@RequestBody Role role) {
why do we need to publicly expose the creating of a new role via?

2022-03-23 16:59 UTC, chumomega commented on src/main/java/com/v2/pranker/controller/PrankerController.java
> +    public ResponseEntity<?>addRoleToPranker(@RequestBody RoleToPrankerForm form) {
why do we need to publicly expose the adding of a role to a user?

2022-03-23 17:00 UTC, Jakarai reviewed
no reason, I changed it during running multiple servers, I changed back

2022-03-23 17:01 UTC, chumomega commented on src/main/java/com/v2/pranker/repos/PrankerRepo.java
> +public interface PrankerRepo extends JpaRepository<Pranker, Long> {
why do we need an interface, can't this just contain all the methods you implemented in the `...service` file

2022-03-23 17:07 UTC, chumomega commented on src/main/java/com/v2/pranker/services/PrankerServiceImpl.java
> +    public void addRoleToPranker(String prankername, String roleName) {
[nit] your variable names aren't consistent

2022-03-23 17:13 UTC, chumomega requested changes
this pr is huge, adds a lot of fundamental changes to how we access the database, and adds a major change in how the project is structured. i don't necessarily think it's wrong or right, but i do think it will make contributing to this project much more complex. 
Path forward: I think we need to come to a consensus on how we want to structure the project, access the database, before moving forward. If we're going to move from pure JDBC to JPA, then we need to do a whole refactor so there is consistency.

2022-03-23 17:21 UTC, Jakarai commented on src/main/java/com/v2/pranker/controller/PrankerController.java
> +    public ResponseEntity<Role>saveRole(@RequestBody Role role) {
Visibility for Spring beans

2022-03-23 17:30 UTC, Jakarai commented on src/main/java/com/v2/pranker/services/PrankerServiceImpl.java
> +    public void addRoleToPranker(String prankername, String roleName) {
These are also already refactored, I wanted to PR in by working parts as opposed to one big PR

2022-03-23 17:34 UTC, Jakarai commented
Btw JPA is built on top of JDBC its handling all the ORM for me.

2022-03-26 17:42 UTC, chumomega commented on src/main/java/com/v2/pranker/controller/PrankerController.java
> +    public ResponseEntity<Role>saveRole(@RequestBody Role role) {
what do you mean by that?

2022-03-26 17:45 UTC, chumomega commented
could we convert to using native jdbc for now? i know jpa has certain benefits, but I'm thinking about ease of development and neither myself nor karen are super familiar with jpa. also(and more importantly imo), we already have the entire codebase built on native jdbc. adding this without a large scale refactor would fracture the codebase and make it more complex.

2022-03-27 19:44 UTC, chumomega approved these changes
approved, but i still feel icky about how huge this pr is and how much is being added without fully grasping what each piece is doing

2022-03-27 20:23 UTC, merged